### ISSUE TITLE
Some tag names in 'ros_tag' table are cut

### ISSUE THREAD

**Issue by pestefo** [elbraulio/ros_gh#11]
There are 1277 tags that looks cut, e.g. : 

| id  | name              |
|-----|-------------------|
| 5   | turtlebot_dash... |
| 9   | turtlebot_cali... |
| 206 | message_genera... |
| 263 | installation_e... |
| 288 | camera_calibra... |
| 305 | sicktoolbox_wr... |
| 306 | xv_11_laser_dr... |
| 348 | trajectory_fil... |

You can get the complete list with this query:

```sql
select *
from ros_tag	
where name like '%...'
```

**Comment by elbraulio** [comment]
these are all the questions that contain these tags:
- [arm_navigationkinematics-for-simple-arms](https://answers.ros.org/question/28767/arm_navigationkinematics-for-simple-arms/)
- [publish-jointstates-from-gazebo](https://answers.ros.org/question/30566/publish-jointstates-from-gazebo/)
- [modifying-mainactivityjava-does-not-result-in-new-apk](https://answers.ros.org/question/30884/modifying-mainactivityjava-does-not-result-in-new-apk/)
- [classnotfoundexception-on-pubsub-tutorial](https://answers.ros.org/question/31601/classnotfoundexception-on-pubsub-tutorial/)

now i'm trying to find out if there is a max length for a tag, maybe that is the reason of the `...` at the end of large named tags..

**Comment by pestefo** [comment]
If there are no more questions using those cut tags, then I'd rather close this issue. We can manually modify the data.

**Comment by elbraulio** [comment]
it seems like the tag was created with that `...` in its name. I had created a question with a larged tag here:

[https://answers.ros.org/question/309073/just-ignore-this-question/](https://answers.ros.org/question/309073/just-ignore-this-question/)

and there is not `...` on my tag `abcdefghijklmnopqrstuvwxyz1234567890`
